name: Terraform Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./autenticacao/LambdaAutenticacao/LambdaAutenticacao

jobs:
  terraform-deploy:
    name: Deploy Infra with Terraform
    runs-on: ubuntu-latest

    env:
        DB_CONECTION_STRING: ${{ secrets.DB_CONECTION_STRING }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_COLLECTION: ${{secrets.DB_COLLECTION}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Lambda Dependencies
      run: |
        cd Lambda
        pip install pymongo -t .  # Instala dependências na pasta atual
        cd ..

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.6"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve