name: Terraform Validation

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./terraform

jobs:
  terraform-validation:
    name: Validate Infra with Terraform
    runs-on: ubuntu-latest

    env:
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.6"

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan